language: node_js
node_js:
  - "6"
install:
  - npm i
  - npm i jii jii-model
services:
  - mysql
before_script:
  - mysql -e "CREATE DATABASE jiitest"
  - mysql -e "CREATE USER jiitest@localhost IDENTIFIED BY 'jiitest'"
  - mysql -e "GRANT ALL PRIVILEGES ON jiitest.* TO jiitest@localhost"
script:
  - nodeunit tests/unit